import front149 from "../images/battle/poketmon/front/poketmon_front149.png";
import back149 from "../images/battle/poketmon/back/poketmon_back149.png";
import front991 from "../images/battle/poketmon/front/poketmon_front991.png";
import back991 from "../images/battle/poketmon/back/poketmon_back991.png";

window.PoketmonType = {
    노말: "노말",
    불꽃: "불꽃",
    물: "물",
    풀: "풀",
    전기: "전기",
    얼음: "얼음",
    격투: "격투",
    독: "독",
    땅: "땅",
    비행: "비행",
    에스퍼: "에스퍼",
    벌레: "벌레",
    바위: "바위",
    고스트: "고스트",
    드래곤: "드래곤",
    악: "악",
    강철: "강철",
    페어리: "페어리",
}
window.PoketmonStatus = {
    정상: "정상",
    독: "독",
    맹독: "맹독",
    화상: "화상",
    마비: "마비",
    잠듦: "잠듦",
    얼음: "얼음",
    혼란: "혼란",
    풀죽음: "풀죽음",
    교체불가: "교체불가",
    헤롱헤롱: "헤롱헤롱",
    기술사용불가:"기술사용불가",
    금제: "금제",
    멸망의노래:"멸망의노래",
    길동무: "길동무",
    저주:"저주",
    분진: "분진",
    소금절이:"소금절이",
}
window.PoketmonNatureType = {
    노력: "노력",
    외로움: "외로움",
    고집: "고집",
    개구쟁이: "개구쟁이",
    용감: "용감",
    대담: "대담",
    장난꾸러기: "장난꾸러기",
    촐랑: "촐랑",
    무사태평: "무사태평",
    조심: "조심",
    의젓: "의젓",
    수줍음: "수줍움",
    덜렁: "덜렁",
    냉정: "냉정",
    차분: "차분",
    얌전: "얌전",
    신중: "신중",
    변덕: "변덕",
    건방: "건방",
    겁쟁이: "검쟁이",
    성금: "성급",
    명랑: "명량",
    천진난만: "천진난만",
    성실: "성실",
}
